#!/bin/bash

#set -x
set -e
IFS=$'\n'       # make newlines the only separator

function Is_File_OK_For_Commit {
  if [ "$1" == "" ]; then
    echo "Please enter a file name"
  	exit 1
  fi
  FILENAME="$1"
  SIZE=$(du -k $FILENAME | awk '{ print $1 }')

  if ((SIZE<50000)) ; then
    echo "  ${SIZE} kb is less than 50 mb.safe for git commit ";
		return 0
  else
    echo "  ${SIZE} kb is greater than 50 mb. not safe for git commit";
		return 1
  fi
}

echo -e "\nChecking to see if any of the changed files exceed the 50 MB limit"
for file in $(git diff --cached --name-only); do
  echo "Checking $file"
  Is_File_OK_For_Commit "$file"
done;
